apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fiber-api.fullname" . }}
  labels:
{{ include "fiber-api.labels" . | indent 4 }}
type: Opaque
data:
  REDIS_HOST: {{ .Values.REDIS_HOST | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD | b64enc | quote }}
  POSTGRES_DB: {{ .Values.POSTGRES_DB | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_USER: {{ .Values.POSTGRES_USER | b64enc | quote }}
