{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fiber-api.serviceAccountName" . }}
  labels:
{{ include "fiber-api.labels" . | indent 4 }}
{{- end -}}
